spring:
  freemarker:
    suffix: .html

  resources:
    static-locations: 'classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, classpath:/META-INF/resources/webjars'

logging:
  level:
    kr:
      kdev:
        demo: DEBUG